apiVersion: apps/v1
kind: Deployment
metadata:
  name: apachekub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proyectokubernetes
  template:
    metadata:
      labels:
        app: proyectokubernetes
    spec:
      containers:
      - name: apache
        image: joeleleazar/proyectokubernetes:latest
        ports:
        - containerPort: 80